"""9 家 LLM 厂商预定义配置：base_url, 模型列表, API Key 申请链接, LiteLLM 前缀"""

PROVIDERS = {
    "openai": {
        "name": "OpenAI",
        "base_url": "https://api.openai.com/v1",
        "api_key_url": "https://platform.openai.com/api-keys",
        "models": [
            "gpt-5.5",
            "gpt-5.5-pro",
            "gpt-5.4",
            "gpt-5.4-mini",
            "gpt-5.4-nano",
        ],
        "api_prefix": "openai/",
        "is_native": True,
        "supports_tools": True,
    },
    "anthropic": {
        "name": "Anthropic",
        "base_url": "https://api.anthropic.com",
        "api_key_url": "https://console.anthropic.com/settings/keys",
        "models": [
            "claude-opus-4.8",
            "claude-sonnet-4.6",
            "claude-haiku-4.5",
        ],
        "api_prefix": "anthropic/",
        "is_native": True,
        "supports_tools": True,
    },
    "google": {
        "name": "Google",
        "base_url": "https://generativelanguage.googleapis.com/v1beta/openai",
        "api_key_url": "https://aistudio.google.com/app/apikey",
        "models": [
            "gemini-3.1-pro",
            "gemini-3.5-flash",
        ],
        "api_prefix": "gemini/",
        "is_native": True,
        "supports_tools": True,
    },
    "deepseek": {
        "name": "DeepSeek",
        "base_url": "https://api.deepseek.com",
        "api_key_url": "https://platform.deepseek.com/api_keys",
        "models": [
            "deepseek-v4-pro",
            "deepseek-v4-flash",
        ],
        "api_prefix": "deepseek/",
        "is_native": True,
        "supports_tools": True,
    },
    "kimi": {
        "name": "Kimi (月之暗面)",
        "base_url": "https://api.moonshot.cn/v1",
        "api_key_url": "https://platform.moonshot.cn/console/api-keys",
        "models": [
            "kimi-k2.6",
            "kimi-k2.5",
            "moonshot-v1-8k",
            "moonshot-v1-32k",
            "moonshot-v1-128k",
        ],
        "api_prefix": "openai/",
        "is_native": False,
        "supports_tools": True,
    },
    "minimax": {
        "name": "MiniMax",
        "base_url": "https://api.minimax.chat/v1",
        "api_key_url": "https://platform.minimaxi.com/user-center/basic-information/interface-key",
        "models": [
            "MiniMax-M3",
            "MiniMax-M2.7",
            "MiniMax-M2.7-highspeed",
            "MiniMax-M2.5",
            "MiniMax-M2.5-highspeed",
            "MiniMax-M2.1",
            "MiniMax-M2.1-highspeed",
            "MiniMax-M2",
        ],
        "api_prefix": "openai/",
        "is_native": False,
        "supports_tools": False,
    },
    "glm": {
        "name": "智谱 GLM (Z.ai)",
        "base_url": "https://open.bigmodel.cn/api/paas/v4",
        "api_key_url": "https://open.bigmodel.cn/usercenter/apikeys",
        "models": [
            "glm-5.1",
            "glm-5",
            "glm-4.7",
            "glm-4.7-flash",
        ],
        "api_prefix": "openai/",
        "is_native": False,
        "supports_tools": True,
    },
    "doubao": {
        "name": "字节豆包 (Doubao)",
        "base_url": "https://ark.cn-beijing.volces.com/api/v3",
        "api_key_url": "https://console.volcengine.com/ark/region:ark+cn-beijing/apiKey",
        "models": [
            "doubao-seed-2.0-pro",
            "doubao-seed-2.0-mini",
        ],
        "api_prefix": "openai/",
        "is_native": False,
        "supports_tools": True,
    },
    "custom": {
        "name": "自定义",
        "base_url": "",
        "api_key_url": "",
        "models": [],
        "api_prefix": "openai/",
        "is_native": False,
        "is_custom": True,
        "supports_tools": True,
    },
}

PROVIDER_ORDER = [
    "openai", "anthropic", "google", "deepseek",
    "kimi", "minimax", "glm", "doubao", "custom",
]
